name: Run tests on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install workspace
        run: pnpm install
      - name: Type check JS library
        working-directory: js
        run: pnpm types
      - name: Build JS library
        working-directory: js
        run: pnpm build
      - name: Type check component library
        working-directory: score-component-lib
        run: pnpm types
      - name: Build component library
        working-directory: score-component-lib
        run: pnpm build
