name: Build & publish npm package to GitHub Packages
on:
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  publish:
    defaults:
      run:
        working-directory: js
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: pnpm install
      - name: Install dependencies
        run: pnpm build
      - name: Publish to GitHub NPM Registry
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
